config/routes.rb
Rails.application.routes.draw do



  root to: "job_posts#index"


  authenticate :client do
    resources :job_posts, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :job_posts, only: [:index, :show]

  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks', sessions: "users/sessions", invitations: 'users/invitations' }
  devise_for :clients, path: 'clients', controllers: { sessions: "clients/sessions" }

  authenticate :user do
    resources :users, only: [ :show ]
  end
  authenticate :client do
    resources :clients, only: [ :show ]
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :job_posts do
    resources :exams
  end
  resources :exams do
    resources :exam_questions
  end
  resources :exam_questions do
    resources :exam_options
  end
  resources :exams do
    resources :tests, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :exam_answers
  resources :test_answers
  resources :tests
end

app/models/job_post.rb
class JobPost < ApplicationRecord
  belongs_to :client, optional: true
  has_many :exams, -> { order "created_at DESC"}, dependent: :destroy, :inverse_of => :job_post
  has_many :tests, through: :exams
  has_many :users, through: :tests
end

app/controllers/job_posts_controller.rb
class JobPostsController < ApplicationController

  def index
    @job_posts = JobPost.all.order("created_at DESC")
  end

  def new
    @job_post = JobPost.new
  end

  def create
    @job_post = JobPost.new(job_post_params)
    if @job_post.save!
      redirect_to @job_post
    else
      render 'new'
    end
  end

  def show
    @job_post = JobPost.find(params[:id])
  end

  def update
    @job_post = JobPost.find(params[:id])
    # binding.pry
    if @job_post.update(job_post_params)
      redirect_to @job_post
    else
      render 'edit'
    end
  end

  def edit
    @job_post = JobPost.find(params[:id])
  end

  def destroy
    @job_post = JobPost.find(params[:id])
    @job_post.destroy
    redirect_to job_posts_path
  end

  private

  def job_post_params
    params.require(:job_post).permit(:title, :content)
  end
end

app/helpers/job_posts_helper.rb
module JobPostsHelper
end

app/views/job_posts/_form.html.erb
<div class="section">
  <%= simple_form_for @job_post do |f| %>
    <div class="field">
      <div class="control">
        <%= f.input :title, input_html: {class: 'input'}, wrapper: false, label_html: {class: 'label'} %>
      </div>
    </div>
    <div class="field">
      <div class="control">
        <%= f.input :content, input_html: {class: 'textarea'}, wrapper: false, label_html: {class: 'label'} %>
      </div>
    </div>
    <%= f.button :submit, class: "button is-primary" %>
  <% end %>
</div>

app/views/job_posts/edit.html.erb
<% content_for :page_title, "Edit Job Post" %>

<%= render 'form' %>

app/views/job_posts/index.html.erb
<% content_for :page_title, "Index" %>

  <% unless current_user || current_client %>
<!--    <section class="section">-->
<!--      <div class="container">-->
<!--        <h1>Welcome to App-Tester! To see the list of job posts, Register as a company or create a user account.</h1>-->
<!--      </div>-->
<!--    </section>-->
    <div class="hero-body">
      <div class="container has-text-centered">
        <h1 class="title">
          Welcome to App-Tester! <br /><br />
          <h3>To see the list of job posts, Register as a company or create a user account.</h3>
        </h1>
      </div>
    </div>
  <% end %>

  <% if current_user || current_client %>
    <section class="section">
      <div class="container">
        <% @job_posts.each do |post| %>
          <div class="card">
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <p class="title is-4"><%= link_to post.title, post %></p>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </section>
  <% end %>

app/views/job_posts/new.html.erb
<% content_for :page_title, "Create A New Post" %>

<%= render 'form' %>

app/views/job_posts/show.html.erb
<% content_for :page_title, @job_post.title %>

<section class="section">
  <div class="container">
    <nav class="level">
      <!-- Left Side -->
      <div class="level-left">
        <h1 class="title">
          <%= @job_post.title %>
        </h1>
      </div>

        <!-- Right Side -->
      <div class="level-right">
        <% if current_user %>
          <p class="button">
            <%= link_to "Take Test", new_exam_test_path(@job_post.exams.first) %>
          </p>
        <% end %>
        <% if current_client %>
          <% if @job_post.exams.any? %>

          <% else %>
          <p class="button">
            <%= link_to "Create Test", :controller => "exams", :action => "new", :id => @job_post.id %>
          </p>
          <% end %>
        <% end %>
        <% if current_client %>
          <p class="level-item">
            <p class="level-item">
              <%= link_to "Edit", edit_job_post_path(@job_post), class: "button" %>
            </p>
          </p>
        <% end %>
        <% if current_client %>
          <p class="level-item">
            <%= link_to "Delete", job_post_path(@job_post), method: :delete, data: {confirm: "Are you sure?"}, class: "button is-danger" %>
          </p>
        <% end %>
      </div>
    </nav>
    <hr />
    <div class="content">
      <%= @job_post.content %>
    </div>
  </div>
</section>