config/routes.rb
Rails.application.routes.draw do



  root to: "job_posts#index"


  authenticate :client do
    resources :job_posts, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :job_posts, only: [:index, :show]

  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks', sessions: "users/sessions", invitations: 'users/invitations' }
  devise_for :clients, path: 'clients', controllers: { sessions: "clients/sessions" }

  authenticate :user do
    resources :users, only: [ :show ]
  end
  authenticate :client do
    resources :clients, only: [ :show ]
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :job_posts do
    resources :exams
  end
  resources :exams do
    resources :exam_questions
  end
  resources :exam_questions do
    resources :exam_options
  end
  resources :exams do
    resources :tests, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :exam_answers
  resources :test_answers
  resources :tests
end

app/models/exam.rb
class Exam < ApplicationRecord
  validates :job_post, presence: true
  belongs_to :job_post
  has_many   :exam_questions, dependent: :destroy, inverse_of: :exam
  has_many   :exam_answers, dependent: :destroy, through: :exam_questions
  accepts_nested_attributes_for :exam_questions, allow_destroy: true
  accepts_nested_attributes_for :exam_answers, allow_destroy: true
  #has_many   :exam_answers, dependent: :destroy, :inverse_of => :exam

  has_many :tests, dependent: :destroy, inverse_of: :exam
  accepts_nested_attributes_for :tests, allow_destroy: true
  has_many :users, through: :tests
end

app/controllers/exams_controller.rb
require 'pry'

class ExamsController < ApplicationController
  before_action :set_exam, only: [:show, :edit, :update, :destroy]

  def index
    @exams = Exam.all.order('name ASC')
  end

  def new
    @exam = Exam.new
    @job_post = JobPost.find(params[:id])
    @exam.job_post_id = @job_post.id
    @exam.name = @job_post.title
    1.times do
      question = @exam.exam_questions.build
      letters = "A", "B", "C", "D"
      letters.each do |letter|
        question.exam_answers.build(:letter => letter)
      end
    end
  end

  def create
    @exam = Exam.new(exam_params)
    if @exam.save!
      redirect_to @exam
    else
      render 'new'
    end
  end

  def show
    @exam = Exam.find(params[:id])
    @exam_questions = ExamQuestion.all
  end

  def update
    @exam = Exam.find(params[:id])
    if @exam.update_attributes(exam_params)
      redirect_to @exam, notice: "Successfully updated exam."
    else
      render 'edit'
    end
  end

  def edit
  end

  def destroy
    @exam = Exam.find(params[:id])
    @exam.destroy
    redirect_to exams_path, notice: "Successfully destroyed exam."
  end

  def set_exam
    @exam = Exam.find(params[:id])
  end

  private

  def exam_params
    params.require(:exam).permit(:name, :job_post_id, exam_questions_attributes: [:description, exam_answers_attributes:[:exam_question_ids, :letter, :answer, :correct]] )
  end
end

app/views/exams/_form.html.erb
<div class="section">
  <%= simple_form_for @exam do |f| %>
    <%= f.input :name, input_html: {class: 'input'}, wrapper: false, label_html: {class: 'label'}  %>
  <div class="field">
    <div class="section">
      <div class="field">
        <div class="control">
          <%= f.hidden_field :job_post_id %>
          <%= f.simple_fields_for :exam_questions do |q| %>
          <br/><br/>
          <div class="field">
            <div class="control">
              <%= q.input :description, input_html: {class: 'textarea'}, wrapper: false, label_html: {class: 'label'}  %>
              <br/><br/>
              <%= q.simple_fields_for :exam_answers do |a| %>
                <%= f.hidden_field :exam_question_ids %>
              <div class="field">
                <div class="control">
                  <fieldset>
                    <%= a.hidden_field :letter %>
                    <%= a.label :letter, a.object.letter %>
<!--                    DO NO CHANGE THIS LINE -->
                    <%= a.input :answer, input_html: {class: 'input'}, wrapper: false, label_html: {class: 'label'}  %>
<!--                    ^^^^^^^^^^^^^^^^^^^^^^ -->
                    <h3>If correct answer, mark this bubble.</h3>
                    <%= a.radio_button :correct, :correct_answer  %><br/><br/>
                  </fieldset>
                </div>
              </div>
              <% end %>
            </div>
          </div>
          <% end %>
          <%= f.button :submit, class: "button is-primary" %>
        </div>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/exams/edit.html.erb
<% content_for :page_name, "Edit Exam" %>

<%= render 'form' %>

app/views/exams/index.html.erb
<% content_for :page_title, "Index" %>

<section class="section">
  <div class="container">
    <% @exams.each do |exam| %>
      <div class="card">
        <div class="card-content">
          <div class="media">
            <div class="media-content">
              <p class="title is-4">
                <h1>
                  <%= link_to "#{exam.name}", exam_path(exam) %>
                </h1>
              </p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/exams/new.html.erb
<% content_for :page_name, "Create A New Exam" %>

<%= render 'form' %>

app/views/exams/show.html.erb
<% content_for :page_name, @exam.job_post.id %>

<section class="section">
  <div class="container">
    <nav class="level">

      <!-- Left Side -->
      <div class="level-left">
        <h1 class="title">
          <%= @exam.job_post.title %>
        </h1>
      </div>

      <!-- Right Side -->
      <div class="level-right">
        <% if current_client %>
          <p class="level-item">
            <%= link_to "Add Question", edit_exam_path(@exam), exam_question: @exam.exam_questions.build, class: "button" %>
          </p>
          <p class="level-item">
            <%= link_to "Delete", exam_path(@exam), method: :delete, data: {confirm: "Are you sure?"}, class: "button is-danger" %>
          </p>
        <% end %>
      </div>
    </nav>



    <hr />
  </div>

  <div class="description">
    <% @exam.exam_questions.each do |q| %>
      <div class="title">
        <div class="media-content">
          <%= q.description %>
        </div>
      </div>
      <% q.exam_answers.each do |a| %>
        <div class="card">
          <div class="card-content">
            <div class="media">
              <div class="media-content">
                <div class="answer">
                  <%= a.letter %>. <%= a.answer %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
      <br />
    <% end %>
  </div>
</section>