config/routes.rb
Rails.application.routes.draw do



  root to: "job_posts#index"


  authenticate :client do
    resources :job_posts, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :job_posts, only: [:index, :show]

  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks', sessions: "users/sessions", invitations: 'users/invitations' }
  devise_for :clients, path: 'clients', controllers: { sessions: "clients/sessions" }

  authenticate :user do
    resources :users, only: [ :show ]
  end
  authenticate :client do
    resources :clients, only: [ :show ]
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :job_posts do
    resources :exams
  end
  resources :exams do
    resources :exam_questions
  end
  resources :exam_questions do
    resources :exam_options
  end
  resources :exams do
    resources :tests, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :exam_answers
  resources :test_answers
  resources :tests
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  include DeviseInvitable::Inviter

  has_many :applicants, class_name: "User"
  has_many :job_posts
  has_many :exams, through: :job_posts
  has_many :exam_questions, through: :exams
end

app/models/exam.rb
class Exam < ApplicationRecord
  validates :job_post, presence: true
  belongs_to :job_post
  has_many   :exam_questions, dependent: :destroy, inverse_of: :exam
  has_many   :exam_answers, dependent: :destroy, through: :exam_questions
  accepts_nested_attributes_for :exam_questions, allow_destroy: true
  accepts_nested_attributes_for :exam_answers, allow_destroy: true
  #has_many   :exam_answers, dependent: :destroy, :inverse_of => :exam

  has_many :tests, dependent: :destroy, inverse_of: :exam
  accepts_nested_attributes_for :tests, allow_destroy: true
  has_many :users, through: :tests
end

app/models/exam_answer.rb
class ExamAnswer < ApplicationRecord
  # belongs_to :exam, optional: true #:inverse_of => :exam_answers
  belongs_to :exam_question
  has_many :test_answers
  accepts_nested_attributes_for :test_answers

  def correct
    self.correct = true
  end

  def exam_answer_params
    params.require(:exam_answer).permit(:exam_question_id, :exam_id, :letter, :correct, :answer)
  end
end

app/models/exam_question.rb
class ExamQuestion < ApplicationRecord
  validates :exam, :presence => true
  belongs_to :exam

  has_many :exam_answers, dependent: :destroy, :inverse_of => :exam_question
  accepts_nested_attributes_for :exam_answers

  scope :correct_answer, -> { ExamAnswer.where(correct: true) }
end

app/models/job_post.rb
class JobPost < ApplicationRecord
  belongs_to :client, optional: true
  has_many :exams, -> { order "created_at DESC"}, dependent: :destroy, :inverse_of => :job_post
  has_many :tests, through: :exams
  has_many :users, through: :tests
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :user
  belongs_to :exam
  has_many :test_answers
  accepts_nested_attributes_for :test_answers, :reject_if => :all_blank, :allow_destroy => true

end

app/models/test_answer.rb
class TestAnswer < ApplicationRecord
  belongs_to :test
  belongs_to :exam_question
  belongs_to :exam_answer

  def test_answer_params
    params.require(:test_answer).permit(:exam_answer_id, :test_id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :recoverable,
         :rememberable, :trackable, :validatable, :confirmable, :omniauthable,
         omniauth_providers: [:facebook, :google_oauth2]

  validates_confirmation_of :password

  def block_from_invitation?
    false
  end

  has_many :tests
  has_many :exams, through: :tests
  has_many :test_answers, through: :tests
  accepts_nested_attributes_for :test_answers
  has_and_belongs_to_many :job_posts


  before_validation :set_provider
  def set_provider
    self[:provider] = "email" if self[:provider].blank?
  end

  before_validation :set_uid
  def set_uid
    self[:uid] = self[:email] if self[:uid].blank? && self[:email].present?
  end

  def confirmed_at
    self.confirmed_at = Time.now
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end

  def self.create_from_provider_data(provider_data)
    where(provider: provider_data.provider, uid: provider_data.uid).first_or_create do |user|
      user.email = provider_data.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end
end

app/controllers/exams_controller.rb
require 'pry'

class ExamsController < ApplicationController
  before_action :set_exam, only: [:show, :edit, :update, :destroy]

  def index
    @exams = Exam.all.order('name ASC')
  end

  def new
    @exam = Exam.new
    @job_post = JobPost.find(params[:id])
    @exam.job_post_id = @job_post.id
    @exam.name = @job_post.title
    1.times do
      question = @exam.exam_questions.build
      letters = "A", "B", "C", "D"
      letters.each do |letter|
        question.exam_answers.build(:letter => letter)
      end
    end
  end

  def create
    @exam = Exam.new(exam_params)
    if @exam.save!
      redirect_to @exam
    else
      render 'new'
    end
  end

  def show
    @exam = Exam.find(params[:id])
    @exam_questions = ExamQuestion.all
  end

  def update
    @exam = Exam.find(params[:id])
    if @exam.update_attributes(exam_params)
      redirect_to @exam, notice: "Successfully updated exam."
    else
      render 'edit'
    end
  end

  def edit
  end

  def destroy
    @exam = Exam.find(params[:id])
    @exam.destroy
    redirect_to exams_path, notice: "Successfully destroyed exam."
  end

  def set_exam
    @exam = Exam.find(params[:id])
  end

  private

  def exam_params
    params.require(:exam).permit(:name, :job_post_id, exam_questions_attributes: [:description, exam_answers_attributes:[:exam_question_ids, :letter, :answer, :correct]] )
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController

  def index
    @tests = Test.all.order("created_at DESC")
  end

  def new
    @exam = Exam.find(params[:exam_id])
    @test = @exam.tests.build
    @exam.exam_questions.each do |exam_question|
      @test.test_answers.build(:exam_question_id => exam_question.id)
    end
  end

  def create
    @exam = Exam.find(params[:exam_id])
    @exam.user_ids = current_user.id
    @test = Test.find_or_initialize_by(params[:exam => :exam_id])
    @test.exam_id = @exam.id
    @test.score = 0
    if @test.test_answers == @exam.exam_questions.correct_answer
      @test.increment!(:score, 10)
    end
    if @test.save
      redirect_to @test
    else
      render 'new'
    end
  end

  def show
    @test = Test.find(params[:id])
  end

  def update
    @test = Test.find(params[:id])

    if @test.update(test_params)
      redirect_to @test
    else
      render 'edit'
    end
  end

  def destroy
    @test = Test.find(params[:id])
    @test.destroy
    redirect_to tests_path
  end

  private

  def test_answer_params
    params.permit(:exam_answer_id, :test_id)
  end

  def test_params
    params.require(:test).permit(:exam_id, :user_id, test_answers_attributes: [:exam_answer_id, :exam_question_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = current_user
    @user.id = current_user.id
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exam_options_helper.rb
module ExamOptionsHelper
end

app/helpers/exam_questions_helper.rb
module ExamQuestionsHelper
end

app/helpers/job_posts_helper.rb
module JobPostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/test_answers_helper.rb
module TestAnswersHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppTester</title>


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <section class="hero is-primary is-medium">
      <!-- Hero head: will stick at the top -->
      <div class="hero-head">
        <nav class="navbar">
          <div class="container">
            <div class="navbar-brand">

              <span class="navbar-burger burger" data-target="navMenu">
              <span></span>
              <span></span>
              <span></span>
            </span>
            </div>
            <div id="navMenu" class="navbar-menu">
              <div class="navbar-end">
                <a class="navbar-item">
<!--                  TODO: Add Take Test functionality-->
                  <%= link_to 'Invite Employee To Take Test', new_user_invitation_path, class: "navbar-item" %>
                </a>
<!--                <a class="navbar-item">-->
<!--                  TODO: Add About Us page-->
                  <%#= link_to 'About Us', about_us_path, class: "navbar-item" %>
<!--                </a>-->
                <% if current_user.class == User %>
                  <a class="navbar-item">
                    <%= link_to "Edit Account Info", edit_user_registration_path, class: "navbar-item" %>
                  </a>
                  <a class="navbar-item">
                    <%= link_to 'Profile Page', "users/:id", class: "navbar-item" %>
                  </a>
                  <a class="navbar-item">
                    <%= link_to 'Employee Sign out', destroy_user_session_path, method: :delete, class: "navbar-item" %>
                <% elsif current_client %>
                  <a class="navbar-item">
                    <%= link_to "Edit Account Info", edit_client_registration_path, class: "navbar-item" %>
                  </a>
                  <a class="navbar-item">
                    <%= link_to 'Profile Page', "clients/:id", class: "navbar-item" %>
                  </a>
                <% elsif unless current_user || current_client %>
                  <a class="navbar-item">
                    <%= link_to 'Employee Sign in', new_user_session_path, class: "navbar-item" %>
                  </a>
                  <a class="navbar-item">
                    <%= link_to 'Employee Sign Up', new_user_registration_path, class: "navbar-item" %>
                <% end %>
                <% else %>
                <% end %>
                  </a>
                </a>
              </div>
            </div>
          </div>
        </nav>
        <script type="text/javascript">
            (function() {
                var burger = document.querySelector('.burger');
                var nav = document.querySelector('#'+burger.dataset.target);

                burger.addEventListener('click', function () {
                    burger.classList.toggle('is-active');
                    nav.classList.toggle('is-active');
                });
                })();
        </script>
      </div>

      <!-- Hero content: will be in the middle -->
      <div class="hero-body">
        <div class="container has-text-centered">
          <h1 class="title">
            App Tester
          </h1>
        </div>
      </div>

      <!-- Hero footer: will stick at the bottom -->
      <div class="hero-foot">
        <nav class="tabs is-boxed is-fullwidth">
          <div class="container">
            <ul>
              <li>
<!--              <%#= link_to 'App-Tester Home', root_path, class: "navbar-item" %></a></li>-->
                <%= link_to 'Home', root_path, class: "navbar-item" %>
              <% if current_client  %>
              <li><%= link_to "Create Job Post", new_job_post_path, class: "navbar-item" %></li>
              <li><%= link_to "Built Tests", exams_path %></li>
              <% end %>
              <li></li>
              <li>
                <% if current_client  %>
                  <%= link_to 'Sign out', destroy_client_session_path, method: :delete %>
                <% elsif current_user.class == User %>

                <% else %>
                  <%= link_to 'Company Sign in', new_client_session_path %>
              </li>
                <li>
                  <%= link_to 'Company Registration', new_client_registration_path %>
                  <% end %>
                </li>

            </ul>
          </div>
        </nav>
      </div>
    </section>
    <%= render 'layouts/alerts' %>
    <%= yield %>
  </body>
</html>